---
- name: Update apt packages
  apt:
    update_cache: true
    cache_valid_time: 86400 #  One day

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ host_name }}"
  when: (host_name is defined) and (host_name|length > 0)
  tags: molecule-notest

- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin

- name: Ensure common packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ packages_to_install }}"

- name: Ensure unwanted packages are uninstalled
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    autoremove: true
    update_cache: true
  loop: "{{ packages_to_uninstall }}"