---
- name: Ensure common packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: [apt-transport-https, ca-certificates, curl, software-properties-common]


# - name: Add Docker GPG key
#   ansible.builtin.apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    # repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker CE
  ansible.builtin.apt:
    # name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
    name: ['docker-ce']
    state: present
    update_cache: true

# - name: Add Docker group
#   ansible.builtin.group:
#     name: docker
#     state: present

# - name: Add user to Docker group
#   ansible.builtin.user:
#     name: "{{ ansible_user }}"
#     groups: docker
#     append: true

- name: Configure Docker daemon options
  ansible.builtin.template:
    src: "templates/docker_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
