## Official configuration - https://docs.renovatebot.com/self-hosted-configuration/
## Helm chart values -https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/values.yaml
renovate:
  enabled: true
  cronjob:
    schedule: "0 13:10 * * *" # every day at 1:10pm
    timeZone: 'Europe/Berlin'
  renovate:
    config: |
      {
        "repositories": ["kannancmohan/homelab"],
        "printConfig": false,
        "dependencyDashboard": true,
        "dependencyDashboardTitle": "Renovate Dashboard"
      }
  existingSecret: renovate-credential
