---
- name: Create self-signed certificate
  hosts: localhost
  # become: yes
  # gather_facts: false
  vars:
    domain_name: "passbolt.pdev.local"
    private_key_name: "passbolt.pdev.local.key"
    private_key_path: "/Users/kannancmohan/Desktop/ssl"
    private_key_file_path: "{{ private_key_path }}/{{ private_key_name }}"
    cert_name: "passbolt.pdev.local.pem"
    cert_path: "/Users/kannancmohan/Desktop/ssl"
    cert_file_path: "{{ cert_path }}/{{ cert_name }}"
    # private_key_passphrase: "password@12212A"
    ## Comment out the private_key_passphrase if you dont need to generate key and certificate using passphrase"
    private_key_passphrase: "{{ lookup('env','CERT_PRIVATE_KEY_PWD') }}"
    passphrase_available: "{{ (private_key_passphrase is defined) and (private_key_passphrase|length > 0) }}"


  tasks:
  - name: Ensure directory exists for key and cert.
    ansible.builtin.file:
      path: "{{ private_key_path }}"
      state: directory

  - ansible.builtin.debug:
      msg: "Generating key and cert using provided passphrase"
    when: passphrase_available

  - name: Ensure (OpenSSL) Private key is present with the default values (4096 bits, RSA)
    community.crypto.openssl_privatekey:
      path: "{{ private_key_file_path }}"
      passphrase: "{{ passphrase_available | ternary(private_key_passphrase, omit) }}"
      cipher: "{{ passphrase_available | ternary('auto', omit) }}"
      force: true # Force regenerate private key

  - name: Ensure certificate signing request (CSR) for self-signed certificate is present
    community.crypto.openssl_csr_pipe:
      privatekey_path: "{{ private_key_file_path }}"
      privatekey_passphrase: "{{ passphrase_available | ternary(private_key_passphrase, omit) }}"
      common_name: "{{ domain_name }}"
      organization_name: KCM, Inc.
      subject_alt_name:
        - "DNS:{{ domain_name }}"
        - "DNS:www.{{ domain_name }}"
        - "DNS:*.{{ domain_name }}"
    register: csr

  - name: Ensure self-signed cert is present
    community.crypto.x509_certificate:
      path: "{{ cert_file_path }}"
      csr_content: "{{ csr.csr }}"
      privatekey_path: "{{ private_key_file_path }}"
      privatekey_passphrase: "{{ passphrase_available | ternary(private_key_passphrase, omit) }}"
      selfsigned_not_after: "+3650d" # roughly 10years. this is the default
      provider: selfsigned
