---
- name: Install & Configure Adguard Home
  hosts: service_hosts
  become: yes
  # gather_facts: false
  vars:
    domain_name: "portainer.pdev.local"
  roles:
    - role: common
    - role: install-docker
      # become: yes
    - role: install-portainer
