{{- if index .Values "global" "external-secrets" "enabled" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-credential
spec:
  target:
    name: renovate-credential
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RENOVATE_TOKEN: |-
          {{ `{{ .github_com_token }}` }}        
        GITHUB_COM_TOKEN: |-
          {{ `{{ .github_com_token }}` }}
        RENOVATE_GIT_AUTHOR: |-
          {{ `{{ .renovate_git_author }}` }}
  data:
    - secretKey: github_com_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: renovate
        property: github_com_token
    - secretKey: renovate_git_author
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: renovate
        property: renovate_git_author
{{- end }}
{{- if index .Values "global" "test-secrets" "enabled" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-credential
stringData:
  RENOVATE_TOKEN: add_your_github_personal_access_token
  GITHUB_COM_TOKEN: add_your_github_personal_access_token
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
{{- end }}