- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: Disable default nginx sites config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Apply new nginx config
  template:
    src: "nginx.conf.j2"
    dest: /etc/nginx/conf.d/nginx.conf

- name: Enable and Start nginx
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: nginx.service
