{{- if index .Values "global" "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-credential
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: dex-credential
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
      type: Opaque
      data:
        ZITADEL_CLIENT_ID: |-
          {{ `{{ .ZITADEL_CLIENT_ID }}` }}
        ZITADEL_CLIENT_SECRET: |-
          {{ `{{ .ZITADEL_CLIENT_SECRET }}` }}
        GRAFANA_SSO_CLIENT_SECRET: |-
          {{ `{{ .GRAFANA_SSO_CLIENT_SECRET }}` }}
        ARGOCD_SSO_CLIENT_SECRET: |-
          {{ `{{ .ARGOCD_SSO_CLIENT_SECRET }}` }}
  data:
    - secretKey: ZITADEL_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: dex_sso
        property: ZITADEL_CLIENT_ID
    - secretKey: ZITADEL_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: dex_sso
        property: ZITADEL_CLIENT_SECRET
    - secretKey: GRAFANA_SSO_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: dex_sso
        property: GRAFANA_SSO_CLIENT_SECRET
    - secretKey: ARGOCD_SSO_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: dex_sso
        property: ARGOCD_SSO_CLIENT_SECRET
{{- end }}