{{- if index .Values "global" "external-secrets" "enabled" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: alertmanager-smtp-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        smtp_auth_password: |-
          {{ `{{ .smtp_auth_password }}` }}
  data:
    - secretKey: smtp_auth_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: alertmanager
        property: smtp_auth_password
{{- end }}