---
- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Setup Portainer directory
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/docker-compose/portainer
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Deploy Portainer using Docker Compose
  ansible.builtin.template:
    src: "templates/portainer_docker_compose.yaml.j2"
    dest: "/home/ubuntu/docker-compose/portainer/docker-compose.yaml"
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Start Portainer
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user_id }}/docker-compose/portainer
    state: present
    restarted: true

# - name: Run Portainer docker-compose up
#   community.docker.docker_compose:
#     project_src: /home/{{ ansible_user_id }}/docker-compose/portainer
#     state: present