---
- name: Update apt packages
  apt:
    update_cache: true
    cache_valid_time: 86400 #  One day

# - name: Ensure common packages are installed
#   apt:
#     name: "{{ item }}"
#     state: present
#     update_cache: true
#   loop: "{{ common_k8s.ubuntu.common_packages }}"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ host_name_prefix + ansible_host.split('.')[-1][-2:] }}"

- name: Disable SWAP
  command: swapoff -a
  changed_when: false # This will never report 'changed' status

- name: Disable SWAP in fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: true

- name: Add the overlay kernel module
  community.general.modprobe:
    name: overlay
    state: present
    persistent: present #  adds module to /etc/modules-load.d/ and params to /etc/modprobe.d/ so that the module will be loaded on reboot

- name: Add the br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present #  adds module to /etc/modules-load.d/ and params to /etc/modprobe.d/ so that the module will be loaded on reboot

- name: Let iptables see bridged traffic
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
