{{- if and (index .Values "global" "external-secrets" "enabled") (eq (index .Values "cert-manager" "certProvider") "letsencrypt_duckdns") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns-credential
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: duckdns-credential
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        token: |-
          {{ `{{ .token }}` }}
  data:
    - secretKey: token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: duckdns
        property: token
{{- end }}