## Official configuration - https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
## Helm chart values - https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  admin:
    existingSecret: grafana-credential
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: default-root-cert-issuer
    hosts:
      - &host grafana.dev.local
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      # the sidecar will search for dashboard config-maps inside this namespace.
      searchNamespace: ALL
    datasources:
      enabled: true
      # the sidecar will search for datasource config-maps inside this namespace.
      searchNamespace: ALL
  envFromSecret: grafana-credential
  ## Grafana's primary configuration ref: http://docs.grafana.org/installation/configuration/
  ### Grafana OIDC
  grafana.ini:
    server:
      root_url: https://grafana.dev.local
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.dev.local/auth
      token_url: https://dex.dev.local/token
      api_url: https://dex.dev.local/userinfo
      # login_attribute_path: preferred_username
      # groups_attribute_path: groups
      # name_attribute_path: name
      # use_pkce: true
      tls_skip_verify_insecure: true # skip self-signed certificate validation
  ### Grafana OIDC ends
  serviceMonitor:
    enabled: true