---
- name: Get K3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0766'

- name: Install K3s in control plane
  command: "/tmp/k3s_install.sh server"
  environment:
    INSTALL_K3S_VERSION: "{{ lookup('env','K3S_VERSION') or k3s_version }}"
    K3S_TOKEN: "{{ lookup('env','K3S_TOKEN') }}"
    INSTALL_K3S_EXEC: "{{ lookup('env', 'K3S_CP_ADDITIONAL_CONFIG') | default('', true) }}"
  changed_when: true

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="
