---
# - name: Check if K3S is already installed
#   ansible.builtin.shell:
#     cmd: 'test -f /usr/local/bin/k3s'
#   register: k3s_installed
#   failed_when: false

- name: Run pre-configuration tasks
  include_tasks: pre_configuration.yml

- name: Install primary control plane
  when:
    - k3s_primary_control_node
  block:
    - name: Install k3s in primary control plane
      include_tasks: control_plane_install.yml
    - name: Conditionally install calico cni-plugin
      include_tasks: calico_cni_install.yml
      when: 
        - lookup('env','INSTALL_CALICO') is defined and lookup('env','INSTALL_CALICO')|bool == true
    # - name: Wait for primary control plane to be ready
    #   include_tasks: wait_for_control_plane.yml
    - name: Write kubeconfig to localhost
      include_tasks: write_kubeconfig_to_local.yml

- name: Install secondary control plane
  when:
    - not k3s_primary_control_node
  # throttle: 1
  block:
    - name: Wait for primary control plane to be ready
      include_tasks: wait_for_primary_control_plane.yml
    - name: Install k3s in secondary control plane
      include_tasks: control_plane_install.yml
