---
- name: "Wait for primary control plane to be ready"
  command:
    cmd: "kubectl get nodes {{ item }}"
  register: nodes
  until:
    - '" Ready "  in nodes.stdout'
  retries: 10
  delay: 5
  with_items: "{{ host_name_prefix + ansible_host.split('.')[-1][-2:] }}"
