---
- name: Check if control plane is available to accept connections
  ansible.builtin.wait_for:
    port: '6443'
    host: "{{ hostvars[groups['k3s_cp_hosts'][0]].ansible_host }}"
    delay: 5
    sleep: 5
    timeout: 300
