---
- name: Get k3s config file from CP
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_base64
  run_once: true
  tags: [ kubeconfig, local-kubeconfig]

- name: Write kube config file to local with the correct cluster address
  copy:
    content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', hostvars[groups['k3s_cp_hosts'][0]].ansible_host ) }}"
    dest: "~/.kube/config"
    mode: 0600
  delegate_to: localhost
  become: false
  run_once: true
  tags: [ kubeconfig, local-kubeconfig]
