---
- name: Converge
  hosts: all

  tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Ensure necessary packages for test are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: ["tzdata"]
      
- ansible.builtin.import_playbook: ../../configuration/main-playbook.yml