service_exposed_ports: [443,80]

CADDY_VERSION: v2.7.6
DUCKDNS_CADDY_PLUGIN_VERSION: latest
GO_VERSION: 1.22.3

DOMAIN_NAME: kcmeu.duckdns.org
CADDY_IP: 192.168.0.22
ADGUARD_IP_PORT: 192.168.0.21:80
PORTAINER_IP_PORT: 192.168.0.30:9102
VAULT_IP_PORT: 192.168.0.23:8000
LOG_FILE: /etc/caddy/access.log
ACME_EMAIL: kannanmohanklm@gmail.com
DUCKDNS_API_TOKEN: "{{ lookup('env','TF_VAR_duckdns_token') }}"