---
- name: Install & Configure Adguard Home
  hosts: service_hosts
  become: yes
  gather_facts: false
  vars:
    ansible_user: root
  # vars_files:
  #   - vars/default.yaml

  tasks:
  - name: Ensure common packages are installed
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop: [debian-keyring, debian-archive-keyring, apt-transport-https, curl]

  - name: Add signing key
    ansible.builtin.apt_key:
      url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
      keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      state: present

  - name: Add Caddy repo
    ansible.builtin.get_url:
      url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
      dest: /etc/apt/sources.list.d/caddy-stable.list
      mode: '0644'

  - name: Install Caddy
    ansible.builtin.apt:
      name: caddy
      update_cache: true
      state: present

  - name: Start Caddy service
    ansible.builtin.systemd:
      name: caddy.service
      daemon_reload: true
      enabled: true
      state: restarted