{{- if index .Values "global" "external-secrets" "enabled" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden-cli.svc.cluster.local:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      #url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.login.{{ `{{ .remoteRef.property }}` }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli.bitwarden-cli.svc.cluster.local:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      #url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      result:
        jsonPath: "$.data.fields[?@.name==\"{{ `{{ .remoteRef.property }}` }}\"].value"
{{- end }}