---
- hosts: k3s_cp_hosts
  become: true
  gather_facts: false
  tasks:
    - name: Uninstall k3s
      command: /usr/local/bin/k3s-uninstall.sh
      changed_when: true

- hosts: k3s_worker_hosts
  become: true
  gather_facts: false
  tasks:
    - name: Uninstall k3s
      command: /usr/local/bin/k3s-agent-uninstall.sh
      changed_when: true
