---
- name: Install & Configure
  hosts: service_hosts
  become: yes
  gather_facts: false
  vars:
    ansible_user: root
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 120

    - name: Gather facts 
      setup:

    - name: Pre configure host
      import_role:
        name: "{{ playbook_dir }}/../../../commons/ansible/roles/host_pre_configure"
      vars:
        host_name: adguard-container

    - name: Ensure necessary directories are created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop: ["/opt/AdGuardHome","/temp/AdGuardHome"]

    - name: Disable internal DNS
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: true
      register: dns_disabled
      loop:
        - { regexp: '#DNS=', line: 'DNS=127.0.0.1' }
        - { regexp: '#DNSStubListener=yes', line: 'DNSStubListener=no' }

    - name: Restart systemd-resolved service
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      when: dns_disabled is defined and dns_disabled.changed
      tags: molecule-notest

    - name: Download Adguard installer
      ansible.builtin.get_url:
        url: https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ ADGUARD_VERSION }}/AdGuardHome_linux_amd64.tar.gz
        checksum: sha256:https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ ADGUARD_VERSION }}/checksums.txt
        dest: /temp/AdGuardHome_linux_amd64.tar.gz

    - name: Unzip Adguard installer
      ansible.builtin.unarchive:
        src: /temp/AdGuardHome_linux_amd64.tar.gz
        dest: /temp
        remote_src: true

    - name: Copy Adguard executable file and set permissions
      ansible.builtin.copy:
        src: /temp/AdGuardHome/AdGuardHome
        dest: /opt/AdGuardHome/
        remote_src: true
        mode: '0755'

    - name: Copy AdGuard config file
      ansible.builtin.template:
        src: templates/adguard-home.config.j2
        dest: /opt/AdGuardHome/AdGuardHome.yaml

    - name: Install Adguard
      ansible.builtin.shell: /opt/AdGuardHome/AdGuardHome -s install
      # tags: molecule-idempotence-notest

    - name: Delete temp directory
      ansible.builtin.file:
        state: absent
        path: "/temp/AdGuardHome"

    - name: Apply ufw settings
      import_role:
        name: "{{ playbook_dir }}/../../../commons/ansible/roles/host_configure_ufw_firewall"
      vars:
        ufw_allowed_ports: ["{{ adguard_port }}", "{{ adguard_dns_port }}"]