---
- name: Install & Configure Adguard Home
  hosts: adguard_hosts
  become: yes
  gather_facts: false
  # vars_files:
  #   - vars/default.yaml


  tasks:
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ host_name_prefix + ansible_host.split('.')[-1][-2:] }}"

  - name: Install Adguard Home
    community.general.snap:
      name:
        - adguard-home

  - name: Make /etc/systemd/resolved.conf.d Directory
    command: mkdir -p /etc/systemd/resolved.conf.d

  - name: Create adguardhome.conf
    copy:
      dest: "/etc/systemd/resolved.conf.d/adguardhome.conf"
      content: |
        [Resolve]
        DNS=127.0.0.1
        DNSStubListener=no

  - name: Backup resolv.conf
    command: mv /etc/resolv.conf /etc/resolv.conf.backup

  - name: Create symbolic link to resolv.conf
    command: ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

  - name: Restart systemd-resolved
    command: systemctl reload-or-restart systemd-resolved

  - name: Copy AdGuard config file
    ansible.builtin.template:
      src: templates/adguard-home.config.j2
      dest: /var/snap/adguard-home/current/AdGuardHome.yaml
      # owner: "{{ ansible_user_id }}"
      # group: "{{ ansible_user_id }}"
      mode: "0644"

  - name: Restart AdGuard service
    ansible.builtin.systemd_service:
      name: snap.adguard-home.adguard-home.service
      state: restarted