---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudnative-pg-cluster
spec:
  ## Number of instances required in the cluster. kubectl get cluster -n cloudnative-pg 
  instances: 2
  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-superuser-secret
  # bootstrap:
  #   initdb:
  #     database: app
  #     owner: app
  #     secret:
  #       name: cnpg-appuser-secret
  storage:
    # storageClass: standard
    size: 1Gi
  monitoring:
    enablePodMonitor: true