# ---
# apiVersion: v1
# kind: Secret
# type: kubernetes.io/basic-auth
# metadata:
#   name: cnpg-appuser-secret
#   labels:
#     cnpg.io/reload: ""
# stringData:
#   username: "app"
#   password: "postgres_app@adminz"
{{- if index .Values "global" "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-superuser-secret
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: cnpg-superuser-secret
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: ""
      type: Opaque
      data:
        admin-user: |-
          {{ `{{ .username }}` }}
        admin-password: |-
          {{ `{{ .password }}` }}
        pgpass: |-
          {{ `{{ .pgpass }}` }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cloudnative_postgres
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cloudnative_postgres
        property: password
    - secretKey: pgpass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: cloudnative_postgres
        property: pgpass
{{- end }}