{{- if index .Values "global" "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-credential
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: zitadel-credential
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        masterkey: |-
          {{ `{{ .masterkey }}` }}
        dbhost: |-
          {{ `{{ .dbhost }}` }}
        dbport: |-
          {{ `{{ .dbport }}` }}
        dbname: |-
          {{ `{{ .dbname }}` }}
        dbuser: |-
          {{ `{{ .dbuser }}` }}
        dbuser_password: |-
          {{ `{{ .dbuser_password }}` }}
        dbadmin: |-
          {{ `{{ .dbadmin }}` }}
        dbadmin_password: |-
          {{ `{{ .dbadmin_password }}` }}
        zitadel_first_user: |-
          {{ `{{ .zitadel_first_user }}` }}
        zitadel_first_pwd: |-
          {{ `{{ .zitadel_first_pwd }}` }}
  data:
    - secretKey: masterkey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: masterkey
    - secretKey: dbhost
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbhost
    - secretKey: dbport
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbport
    - secretKey: dbname
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbname
    - secretKey: dbuser
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbuser
    - secretKey: dbuser_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbuser_password
    - secretKey: dbadmin
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbadmin
    - secretKey: dbadmin_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: dbadmin_password
    - secretKey: zitadel_first_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: zitadel_first_user
    - secretKey: zitadel_first_pwd
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: zitadel_sso
        property: zitadel_first_pwd
{{- end }}