---
# dependency:
#   name: galaxy
driver:
  name: docker
platforms:
  - name: adguard_instance1
    image: custom-ubuntu:22.04
    dockerfile: Dockerfile
    privileged: true
    published_ports:
      - "8081:80"
    networks:
      - name: adguard_network
    # pre_build_image: true
provisioner:
  name: ansible
  # playbooks:
  #   converge: ./converge.yml
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp
  inventory: # added so make use of inventory group 'service_hosts'
    hosts:
      all:
        hosts:
        children:
          service_hosts:
            hosts:
              adguard_instance1:
verifier:
  name: testinfra
scenario:
  test_sequence: # added so as to skip 'idempotence' check while executing 'molecule test'
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - cleanup
    - destroy