---
driver:
  name: docker
platforms:
  - name: adguard_instance1
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp
  inventory: # added so make use of inventory group 'service_hosts'
    hosts:
      all:
        hosts:
        children:
          service_hosts:
            hosts:
              adguard_instance1:
verifier:
  name: testinfra
scenario:
  test_sequence: # added so as to skip 'idempotence' check while executing 'molecule test'
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - verify
    - cleanup
    - destroy