---
- name: Verify
  hosts: all

  tasks:
    - name: Check if file exists
      ansible.builtin.stat:
        path: /opt/AdGuardHome/AdGuardHome.yaml
      register: file_exists_reg

    - ansible.builtin.assert:
        that: file_exists_reg.stat.exists

    - name: Populate services facts
      ansible.builtin.service_facts:
      
    - name: Check services up
      ansible.builtin.assert:
        that:
          - ansible_facts.services['AdGuardHome'].state == "running"

    - name: Verify service web requests.
      ansible.builtin.uri:
        url: http://localhost/
        status_code: 200

    - name: Check if port 53 is listening
      ansible.builtin.wait_for:
        port: 53
        timeout: 10
        msg: "Timeout waiting for 53 to respond"