---
- name: Verify
  hosts: all

  tasks:
    # check that the file exists
    - stat:
        path: /opt/AdGuardHome/AdGuardHome.yaml
      register: p

    - assert:
        that:
          - p.stat.exists

    # - name: Verify Apache is serving web requests.
    #   ansible.builtin.uri:
    #     url: http://192.168.0.30/
    #     status_code: 200