---
- name: Install & Configure
  hosts: service_hosts
  become: yes
  gather_facts: false
  vars:
    ansible_user: root
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 120

    - name: Gather facts 
      setup:

    - name: Pre configure host
      import_role:
        name: "{{ playbook_dir }}/../../../commons/ansible/roles/host_pre_configure"
      vars:
        host_name: adguard-container

    - name: Ensure necessary directories are created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop: ["/opt/AdGuardHome","/temp/AdGuardHome"]

    - name: Disable internal DNS
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "#DNSStubListener=yes"
        line: "DNSStubListener=no"
        backup: true
      register: dns_disabled

    - name: Restart service systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      when: dns_disabled is defined and dns_disabled.changed

    - name: Download Adguard installer
      ansible.builtin.get_url:
        url: https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ ADGUARD_VERSION }}/AdGuardHome_linux_amd64.tar.gz
        checksum: sha256:https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ ADGUARD_VERSION }}/checksums.txt
        dest: /temp/AdGuardHome_linux_amd64.tar.gz

    - name: Unzip Adguard installer
      ansible.builtin.unarchive:
        src: /temp/AdGuardHome_linux_amd64.tar.gz
        dest: /temp
        remote_src: true

    - name: Copy executable file and set permissions
      ansible.builtin.copy:
        src: /temp/AdGuardHome/AdGuardHome
        dest: /opt/AdGuardHome/
        remote_src: true
        mode: a+x

    - name: Copy AdGuard config file
      ansible.builtin.template:
        src: templates/adguard-home.config.j2
        dest: /opt/AdGuardHome/AdGuardHome.yaml
        # owner: "{{ ansible_user }}"
        # group: "{{ ansible_user }}"
        mode: "0644"

    - name: Install Adguard
      ansible.builtin.shell: /opt/AdGuardHome/AdGuardHome -s install


