{{- if index .Values "global" "external-secrets" "enabled" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credential
  #annotations: null
spec:
  #refreshInterval: 15s
  target:
    name: grafana-credential
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: |-
          {{ `{{ .username }}` }}
        admin-password: |-
          {{ `{{ .password }}` }}
        GRAFANA_SSO_CLIENT_SECRET: |-
          {{ `{{ .sso_client_secret }}` }}
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana
        property: password
    - secretKey: sso_client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana
        property: sso_client_secret
{{- end }}
{{- if index .Values "global" "test-secrets" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credential
stringData:
  admin-user: admin@grafana.com
  admin-password: Admin@grafana123.com
  GRAFANA_SSO_CLIENT_SECRET: 264760171249599008@testproject
{{- end }}